# ========= BASE AMBIENT (Simple) ========= 
FROM node:20 AS base

WORKDIR /app

# ========= DEVELOPMENT AMBIENT (Debug) ========= 
FROM base AS development

WORKDIR /app/frontend

RUN apt-get update && apt-get install -y --no-install-recommends \
    git curl && rm -rf /var/lib/apt/lists/*

# ========= BUILDER AMBIENT (Dependencies & Package.json) =========
FROM base AS builder

WORKDIR /app/frontend

COPY app/frontend/package.*json ./

RUN npm ci

COPY app/frontend/ ./
RUN npm run build

# ========= FINAL AMBIENT (Production) =========
FROM nginx:alpine AS final

WORKDIR /app/frontend

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]