# ========= BASE AMBIENT (Simple) ========= 
FROM python:3.11-slim AS base

WORKDIR /app

# ========= DEVELOPMENT AMBIENT (Debug) ========= 
FROM base AS development

WORKDIR /app/backend

RUN apt-get update && apt-get install -y --no-install-recommends \
    git curl vim && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir debugpy ipython --break-system-packages

# ========= BUILDER AMBIENT (Dependencies) =========
FROM base AS builder

WORKDIR /app/backend

COPY app/backend/requirements.txt dependencies/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt --break-system-packages

# ========= FINAL AMBIENT (Production) =========
FROM base AS final

WORKDIR /app/backend

COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY app/backend/ .

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]